#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

usage() {
    cat <<'USAGE'
Usage:
  scripts/smoke/disposable-vm-evidence-runner.sh install [scenario]
  scripts/smoke/disposable-vm-evidence-runner.sh reverify

Runs the public-artifact evidence harness on a disposable VM and writes:

  - a full local command log, and
  - a Markdown report skeleton that can be reviewed, sanitized, and copied into
    the related GitHub issue.

Common environment:
  WAYFINDR_EVIDENCE_TARGET_DIR   Persistent install directory.
                                  Default: /opt/wayfindr-evidence
  WAYFINDR_EVIDENCE_APP_URL      Public or VM-local app URL.
                                  Default: http://127.0.0.1:18080
  WAYFINDR_EVIDENCE_PROJECT      Docker Compose project name.
  WAYFINDR_EVIDENCE_REPORT_DIR   Report/log directory.
                                  Default: <target>/evidence-reports
  WAYFINDR_EVIDENCE_RUN_ID       Stable report identifier.

Install-specific environment:
  WAYFINDR_EVIDENCE_SCENARIO     Harness scenario.
                                  Default: clean-install-latest
  WAYFINDR_EVIDENCE_AGENT_EMAIL  Synthetic agent email.
  WAYFINDR_EVIDENCE_AGENT_PASSWORD
                                  Synthetic agent password. Generated if unset.
  WAYFINDR_EVIDENCE_SITE_PUBLIC_KEY
                                  Synthetic site public key. Generated if unset.

Reverify uses <report-dir>/last-run.env when present, so the VM can be rebooted
and rechecked without retyping the synthetic credentials.
USAGE
}

die() {
    printf '%s\n' "$1" >&2
    exit 1
}

sanitize_name() {
    printf '%s' "$1" \
        | tr '[:upper:]' '[:lower:]' \
        | tr -cs '[:alnum:]-' '-' \
        | sed -E 's/^-+//; s/-+$//; s/-+/-/g'
}

require_command() {
    command -v "$1" >/dev/null 2>&1 || die "Missing required command: $1"
}

ensure_target_dir() {
    if [ -d "$TARGET_DIR" ]; then
        mkdir -p "$REPORT_DIR"
        chmod 700 "$REPORT_DIR" 2>/dev/null || true
        return
    fi

    case "$TARGET_DIR" in
        /opt/wayfindr-evidence|/opt/wayfindr-evidence/*)
            if command -v sudo >/dev/null 2>&1; then
                sudo mkdir -p "$TARGET_DIR"
                sudo chown "$(id -u):$(id -g)" "$TARGET_DIR"
            else
                mkdir -p "$TARGET_DIR"
            fi
            ;;
        *)
            mkdir -p "$TARGET_DIR"
            ;;
    esac

    mkdir -p "$REPORT_DIR"
    chmod 700 "$REPORT_DIR" 2>/dev/null || true
}

write_state_file() {
    umask 077
    {
        printf 'export WAYFINDR_EVIDENCE_SCENARIO=%q\n' "$SCENARIO"
        printf 'export WAYFINDR_EVIDENCE_TARGET_DIR=%q\n' "$TARGET_DIR"
        printf 'export WAYFINDR_EVIDENCE_APP_URL=%q\n' "$APP_URL"
        printf 'export WAYFINDR_EVIDENCE_PROJECT=%q\n' "$PROJECT_NAME"
        printf 'export WAYFINDR_EVIDENCE_AGENT_EMAIL=%q\n' "$AGENT_EMAIL"
        printf 'export WAYFINDR_EVIDENCE_AGENT_PASSWORD=%q\n' "$AGENT_PASSWORD"
        printf 'export WAYFINDR_EVIDENCE_SITE_PUBLIC_KEY=%q\n' "$SITE_PUBLIC_KEY"
    } > "$STATE_FILE"
}

load_state_file() {
    [ -f "$STATE_FILE" ] || return 0

    # The state file is generated by this script with shell-escaped synthetic
    # evidence variables and mode 0600 so a reboot reverify can reuse them.
    # shellcheck disable=SC1090
    . "$STATE_FILE"
}

read_env_value() {
    local key="$1"
    local env_file="$TARGET_DIR/.env"

    grep -E "^[[:space:]]*(export[[:space:]]+)?$key=" "$env_file" 2>/dev/null \
        | tail -1 \
        | sed -E "s/^[[:space:]]*(export[[:space:]]+)?$key=//; s/^\"//; s/\"$//; s/^'//; s/'$//" || true
}

compose() {
    COMPOSE_PROJECT_NAME="$PROJECT_NAME" docker compose \
        --project-name "$PROJECT_NAME" \
        --env-file "$TARGET_DIR/.env" \
        -f "$TARGET_DIR/compose.yml" \
        "$@"
}

compose_exec() {
    compose exec -T web "$@"
}

first_line() {
    sed -n '1p'
}

collect_text() {
    "$@" 2>/dev/null || true
}

collect_release_identity() {
    if [ ! -f "$TARGET_DIR/.env" ] || [ ! -f "$TARGET_DIR/compose.yml" ]; then
        return
    fi

    collect_text compose_exec sh -c 'test -f /etc/wayfindr/version && cat /etc/wayfindr/version || true' \
        | first_line
}

collect_release_commit() {
    if [ ! -f "$TARGET_DIR/.env" ] || [ ! -f "$TARGET_DIR/compose.yml" ]; then
        return
    fi

    collect_text compose_exec php -r '$p="/etc/wayfindr/release.json"; if (is_file($p)) { $j=json_decode(file_get_contents($p), true); echo $j["commit"] ?? ""; }' \
        | first_line
}

write_report() {
    local exit_status="$1"
    local result="pass"
    local image=""
    local digest=""
    local release=""
    local commit=""
    local os=""
    local kernel=""
    local docker_text=""
    local compose_text=""

    if [ "$exit_status" -ne 0 ]; then
        result="fail"
    fi

    image="$(read_env_value WAYFINDR_IMAGE)"
    if [ -n "$image" ]; then
        digest="$(docker image inspect "$image" --format '{{range .RepoDigests}}{{println .}}{{end}}' 2>/dev/null | sed '/^$/d' | first_line || true)"
    fi

    release="$(collect_release_identity)"
    commit="$(collect_release_commit)"
    os="$(collect_text lsb_release -ds | first_line)"
    if [ -z "$os" ] && [ -f /etc/os-release ]; then
        os="$(sed -n 's/^PRETTY_NAME=//p' /etc/os-release | sed -E 's/^"//; s/"$//' | first_line)"
    fi
    kernel="$(collect_text uname -a | first_line)"
    docker_text="$(collect_text docker version --format '{{.Server.Version}} {{.Server.Os}}/{{.Server.Arch}}' | first_line)"
    compose_text="$(collect_text docker compose version --short | first_line)"

    cat > "$REPORT_FILE" <<REPORT
# Disposable VM Evidence — $SCENARIO — $(date +%F)

## Summary

- Scenario: $SCENARIO
- Action: $ACTION
- Result: $result
- Exit status: $exit_status
- Date/time and timezone: $(date -Is)
- Related issue(s): #663, #664, #668
- Public artifact tested: ${release:-unknown}

## VM Baseline

- VM purpose: clean install / upgrade / backup-restore / rollback / reboot
- Base OS: ${os:-unknown}
- Kernel: ${kernel:-unknown}
- Docker version: ${docker_text:-unknown}
- Docker Compose version: ${compose_text:-unknown}
- Network shape: replace with sanitized public HTTPS / private LAN / tunnel / local-only
- Isolation statement: replace with fresh-image or reset-snapshot details.

## Artifact Identity

- Installer source: public installer selected by \`scripts/smoke/public-artifact-install.sh\`
- Starting release, if upgrade: see log
- Target release: ${release:-unknown}
- Release manifest URL: see log
- Commit SHA: ${commit:-unknown}
- Image tag: ${image:-unknown}
- Image digest: ${digest:-unknown}

## Local Evidence Files

- Command log on VM: \`$LOG_FILE\`
- Runner state file on VM: \`$STATE_FILE\`

Review the log before copying any excerpts into GitHub. Do not paste secrets,
cookies, private DNS, private IP inventory, provider IDs, or real support data.

## Scenario Checks

- [ ] Clean install completed from public artifact.
- [ ] \`/setup\` was reachable and first synthetic operator/account owner was created.
- [ ] \`/up\` returned success.
- [ ] Web, queue, backup queue, scheduler, Reverb, Postgres, Redis, and storage were checked.
- [ ] Support loop passed with synthetic visitor and agent data.
- [ ] Backup completed.
- [ ] Restore completed and post-restore data check passed.
- [ ] Upgrade preflight/advisory behavior matched expectation.
- [ ] Upgrade preserved synthetic data.
- [ ] Rollback behavior matched documented support for the tested span.
- [ ] Reboot recovery required no manual intervention, or intervention is documented.

## Findings

| ID | Severity | Finding | Evidence | Proposed follow-up |
| --- | --- | --- | --- | --- |
| VM-001 | blocker/high/medium/low |  |  |  |

## Boundary

This report only proves the exact scenario, artifact, host, and date above. If
this was a hosted or local-only run, it does not prove bare-metal VM reboot,
operator-managed DNS/TLS, real mail delivery, offsite backups, or production
restore posture.

## Redaction Confirmation

- [ ] No secrets, tokens, cookies, private DNS, private IP inventory, provider IDs, or real support data included.
- [ ] Hostnames/IPs are sanitized.
- [ ] Synthetic users/sites/conversations/tickets used.
REPORT
}

run_with_log() {
    local exit_status

    set +e
    if [ "$ACTION" = "install" ]; then
        WAYFINDR_EVIDENCE_SCENARIO="$SCENARIO" \
            WAYFINDR_EVIDENCE_TARGET_DIR="$TARGET_DIR" \
            WAYFINDR_EVIDENCE_APP_URL="$APP_URL" \
            WAYFINDR_EVIDENCE_PROJECT="$PROJECT_NAME" \
            WAYFINDR_EVIDENCE_AGENT_EMAIL="$AGENT_EMAIL" \
            WAYFINDR_EVIDENCE_AGENT_PASSWORD="$AGENT_PASSWORD" \
            WAYFINDR_EVIDENCE_SITE_PUBLIC_KEY="$SITE_PUBLIC_KEY" \
            WAYFINDR_EVIDENCE_KEEP=1 \
            "$ROOT_DIR/scripts/smoke/public-artifact-install.sh" 2>&1 | tee "$LOG_FILE"
        exit_status="${PIPESTATUS[0]}"
    else
        WAYFINDR_EVIDENCE_TARGET_DIR="$TARGET_DIR" \
            WAYFINDR_EVIDENCE_APP_URL="$APP_URL" \
            WAYFINDR_EVIDENCE_PROJECT="$PROJECT_NAME" \
            WAYFINDR_EVIDENCE_AGENT_EMAIL="$AGENT_EMAIL" \
            WAYFINDR_EVIDENCE_AGENT_PASSWORD="$AGENT_PASSWORD" \
            WAYFINDR_EVIDENCE_SITE_PUBLIC_KEY="$SITE_PUBLIC_KEY" \
            WAYFINDR_EVIDENCE_REQUIRE_SUPPORT_LOOP=1 \
            "$ROOT_DIR/scripts/smoke/public-artifact-reverify.sh" 2>&1 | tee "$LOG_FILE"
        exit_status="${PIPESTATUS[0]}"
    fi
    set -e

    return "$exit_status"
}

ACTION="${1:-install}"
case "$ACTION" in
    -h|--help)
        usage
        exit 0
        ;;
    install|reverify)
        ;;
    *)
        usage >&2
        exit 2
        ;;
esac

TARGET_DIR="${WAYFINDR_EVIDENCE_TARGET_DIR:-/opt/wayfindr-evidence}"
REPORT_DIR="${WAYFINDR_EVIDENCE_REPORT_DIR:-$TARGET_DIR/evidence-reports}"
STATE_FILE="$REPORT_DIR/last-run.env"

if [ "$ACTION" = "reverify" ]; then
    load_state_file

    if [ ! -f "$STATE_FILE" ] \
        && { [ -z "${WAYFINDR_EVIDENCE_AGENT_EMAIL:-}" ] \
            || [ -z "${WAYFINDR_EVIDENCE_AGENT_PASSWORD:-}" ] \
            || [ -z "${WAYFINDR_EVIDENCE_SITE_PUBLIC_KEY:-}" ]; }; then
        die "Reverify needs $STATE_FILE from the install run, or explicit synthetic agent/site credentials in the environment."
    fi
fi

SCENARIO="${2:-${WAYFINDR_EVIDENCE_SCENARIO:-clean-install-latest}}"
SCENARIO_SLUG="$(sanitize_name "$SCENARIO")"
[ -n "$SCENARIO_SLUG" ] || SCENARIO_SLUG="custom"
RUN_ID="${WAYFINDR_EVIDENCE_RUN_ID:-$(date -u +%Y%m%dt%H%M%sz)-$SCENARIO_SLUG}"
APP_URL="${WAYFINDR_EVIDENCE_APP_URL:-http://127.0.0.1:18080}"
PROJECT_NAME="${WAYFINDR_EVIDENCE_PROJECT:-wayfindr-evidence-$RUN_ID}"
AGENT_EMAIL="${WAYFINDR_EVIDENCE_AGENT_EMAIL:-agent+$RUN_ID@example.test}"
AGENT_PASSWORD="${WAYFINDR_EVIDENCE_AGENT_PASSWORD:-$(openssl rand -hex 24)}"
SITE_PUBLIC_KEY="${WAYFINDR_EVIDENCE_SITE_PUBLIC_KEY:-site_${SCENARIO_SLUG//-/_}}"
LOG_FILE="$REPORT_DIR/$RUN_ID-$ACTION.log"
REPORT_FILE="$REPORT_DIR/$RUN_ID-$ACTION.md"

require_command curl
require_command docker
require_command grep
require_command openssl
require_command sed
require_command tee

ensure_target_dir
write_state_file

if run_with_log; then
    status=0
else
    status=$?
fi

write_report "$status"

cat <<SUMMARY

== Disposable VM evidence runner summary ==
Action: $ACTION
Scenario: $SCENARIO
Exit status: $status
Log: $LOG_FILE
Report: $REPORT_FILE

Next steps:
1. Review the log and report for secrets or private infrastructure details.
2. Replace placeholders in the report.
3. Copy the sanitized report into the relevant GitHub issue.
SUMMARY

exit "$status"
