<?php

namespace App\Http\Controllers\Api\V1;

use App\Events\ConversationMessageCreated;
use App\Http\Controllers\Controller;
use App\Models\ApiToken;
use App\Models\Conversation;
use App\Models\ConversationMessage;
use App\Models\Site;
use App\Models\Visitor;
use App\Rules\DecodableCursor;
use App\Support\Api\ApiIdempotency;
use App\Support\Api\ApiScope;
use App\Support\Api\V1\Payload;
use App\Support\Conversations\ConversationLifecycleLog;
use App\Support\Mail\ConversationReplyMailer;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Validation\ValidationException;
use Throwable;

/**
 * Conversations in the deliberately narrow public contract (ADR 0018).
 *
 * Every query begins from the token's site ids. Not "and then check the account
 * matches" -- an isolation check that runs after loading is one somebody can
 * forget to write, and its absence looks exactly like working code.
 */
class ConversationController extends Controller
{
    public function store(Request $request, ApiIdempotency $idempotency): JsonResponse
    {
        $scope = ApiScope::fromRequest($request);

        $validated = $request->validate([
            'site_id' => ['required', 'integer'],
            'visitor_id' => ['required', 'integer'],
            'subject' => ['nullable', 'string', 'max:255'],
        ]);

        $result = $idempotency->run(
            $request,
            $validated,
            'conversation',
            function (ApiToken $token) use ($scope, $validated): Conversation {
                // A shared lock makes the archive decision and the insert one
                // operation. Archiving needs an exclusive update lock, so it
                // either lands before this and the write is refused, or after
                // the conversation has committed.
                $site = Site::query()
                    ->whereIn('id', $scope->writableSiteIdsQuery())
                    ->whereKey($validated['site_id'])
                    ->sharedLock()
                    ->first();

                if ($site === null) {
                    $this->invalidReference('site_id');
                }

                $visitor = Visitor::query()
                    ->where('site_id', $site->id)
                    ->whereKey($validated['visitor_id'])
                    // The presence pruner takes this same lock before its final
                    // delete check. Whichever arrives second therefore sees
                    // the other's committed contact decision instead of
                    // inserting against a visitor deleted after lookup.
                    ->lockForUpdate()
                    ->first();

                if ($visitor === null) {
                    // Missing, another account, another site: one answer. An
                    // integration cannot use validation as an id oracle.
                    $this->invalidReference('visitor_id');
                }

                // Opening support work is contact. Besides telling the live
                // board the truth, clearing this while the row is locked makes
                // the pruner's final predicate false before the FK insert.
                $visitor->forceFill(['presence_only' => false])->save();

                $conversation = Conversation::query()->create([
                    'site_id' => $site->id,
                    'visitor_id' => $visitor->id,
                    'support_code' => Conversation::generateSupportCode(),
                    'status' => 'open',
                    'subject' => $validated['subject'] ?? null,
                    'metadata' => ['channel' => 'api'],
                ]);

                $conversation->auditEvents()->create([
                    'account_id' => $site->account_id,
                    'site_id' => $site->id,
                    'actor_type' => $token->getMorphClass(),
                    'actor_id' => $token->id,
                    'action' => 'conversation.created',
                    'metadata' => ['source' => 'api'],
                    'occurred_at' => now(),
                ]);

                return $conversation;
            },
            fn (int $id) => Conversation::query()
                ->whereIn('site_id', $scope->siteIdsQuery())
                ->whereKey($id)
                ->first(),
        );

        return response()
            // A write-only token does not gain the read surface through its
            // response. Everything here is either caller-supplied or the
            // opaque handle generated by this write.
            ->json(['data' => Payload::createdConversation($result->resource, $validated)], 201)
            ->header('Idempotent-Replayed', $result->replayed ? 'true' : 'false');
    }

    public function index(Request $request): JsonResponse
    {
        $scope = ApiScope::fromRequest($request);

        $validated = $request->validate([
            'site_id' => ['nullable', 'integer'],
            'status' => ['nullable', 'string', 'in:open,closed'],
            'per_page' => ['nullable', 'integer', 'min:1', 'max:100'],
            'cursor' => ['nullable', 'string', new DecodableCursor],
        ]);

        $conversations = Conversation::query()
            ->whereIn('site_id', $scope->siteIdsQuery())
            ->when(isset($validated['site_id']), fn ($query) => $query->whereIn(
                'site_id',
                // Can only narrow. Asking for a site the token cannot reach
                // matches nothing rather than being ignored -- an ignored
                // filter is a silent scope escalation.
                $scope->includesSite((int) $validated['site_id']) ? [(int) $validated['site_id']] : [],
            ))
            ->when(isset($validated['status']), fn ($query) => $query->where('status', $validated['status']))
            // Newest first, with `id` breaking ties: cursor pagination needs a
            // total order, and `created_at` alone is not one.
            ->orderByDesc('created_at')
            ->orderByDesc('id')
            ->cursorPaginate($validated['per_page'] ?? 25, ['*'], 'cursor', $validated['cursor'] ?? null);

        return response()->json(Payload::page($conversations, Payload::conversation(...)));
    }

    public function show(Request $request, string $supportCode): JsonResponse
    {
        $conversation = $this->find($request, $supportCode);

        return response()->json(['data' => Payload::conversation($conversation)]);
    }

    public function messages(Request $request, string $supportCode): JsonResponse
    {
        $conversation = $this->find($request, $supportCode);

        $validated = $request->validate([
            'per_page' => ['nullable', 'integer', 'min:1', 'max:100'],
            'cursor' => ['nullable', 'string', new DecodableCursor],
        ]);

        $messages = $conversation->messages()
            // Oldest first: a transcript read in reverse is not a transcript.
            ->orderBy('created_at')
            ->orderBy('id')
            ->cursorPaginate($validated['per_page'] ?? 50, ['*'], 'cursor', $validated['cursor'] ?? null);

        return response()->json(Payload::page($messages, Payload::message(...)));
    }

    public function storeMessage(
        Request $request,
        string $supportCode,
        ApiIdempotency $idempotency,
        ConversationLifecycleLog $lifecycle,
        ConversationReplyMailer $replyMailer,
    ): JsonResponse {
        $scope = ApiScope::fromRequest($request);
        $validated = $request->validate([
            'body' => ['required', 'string', 'max:4000'],
        ]);

        $validated['body'] = trim($validated['body']);

        if ($validated['body'] === '') {
            throw ValidationException::withMessages([
                'body' => 'The body field is required.',
            ]);
        }

        $result = $idempotency->run(
            $request,
            $validated,
            'conversation_message',
            function (ApiToken $token) use ($scope, $supportCode, $validated, $lifecycle): ConversationMessage {
                $candidate = Conversation::query()
                    ->whereIn('site_id', $scope->writableSiteIdsQuery())
                    ->where('support_code', $supportCode)
                    ->firstOrFail();

                $site = Site::query()->whereKey($candidate->site_id)->sharedLock()->first();

                if ($site === null || $site->isArchived() || ! $scope->includesWritableSite((int) $site->id)) {
                    abort(404);
                }

                $conversation = Conversation::query()
                    ->whereKey($candidate->id)
                    ->where('site_id', $site->id)
                    ->lockForUpdate()
                    ->firstOrFail();

                $previousStatus = (string) $conversation->status;

                $message = $conversation->messages()->create([
                    // The token is the author. It is support-side for visitor
                    // presentation, but it is not a User and therefore cannot
                    // impersonate a human in response-time or workload data.
                    'sender_type' => $token->getMorphClass(),
                    'sender_id' => $token->id,
                    'type' => 'text',
                    'body' => $validated['body'],
                    'metadata' => ['channel' => 'api'],
                ]);

                $conversation->forceFill([
                    'status' => 'open',
                    'closed_at' => null,
                    'last_message_at' => $message->created_at,
                ])->save();

                // The channel does not change the lifecycle rule: a message on
                // a closed conversation reopens it. The actor remains the API
                // token, so reporting can distinguish automation from a human.
                $lifecycle->replyReopenedIfClosed($conversation, $token, $previousStatus);

                return $message;
            },
            fn (int $id) => ConversationMessage::query()
                ->whereKey($id)
                ->whereHas('conversation', fn ($query) => $query->whereIn('site_id', $scope->siteIdsQuery()))
                ->first(),
        );

        /** @var ConversationMessage $message */
        $message = $result->resource;
        $message->loadMissing(['sender', 'attachments', 'conversation.site', 'conversation.visitor']);

        if (! $result->replayed) {
            // Persistence is the acceptance boundary. Reverb happens after
            // commit, so an unavailable transport does not turn a stored
            // idempotent write into a retry-inducing 500. Unlike the durable
            // email handoff below, this live announcement only happens once.
            try {
                event(new ConversationMessageCreated($message));
            } catch (Throwable $exception) {
                Log::error('API message stored, but announcing it failed.', [
                    'conversation_message_id' => $message->id,
                    'exception' => $exception->getMessage(),
                ]);
            }
        }

        // Unlike the realtime announcement, email delivery is durable work.
        // A replay must retry it when the first process exited after the write
        // committed or a queue push failed. The mailer locks the message and
        // no-ops once its delivery marker has committed, so successful sends
        // are still queued only once.
        try {
            $replyMailer->send($message);
        } catch (Throwable $exception) {
            Log::error('API message stored, but queuing its email delivery failed.', [
                'conversation_message_id' => $message->id,
                'exception' => $exception->getMessage(),
            ]);
        }

        return response()
            ->json(['data' => Payload::createdMessage($message)], 201)
            ->header('Idempotent-Replayed', $result->replayed ? 'true' : 'false');
    }

    private function find(Request $request, string $supportCode): Conversation
    {
        $scope = ApiScope::fromRequest($request);

        // 404 rather than 403 for a conversation outside the scope. Telling a
        // caller that a support code exists but is not theirs confirms it
        // exists, and support codes are short enough to guess at.
        return Conversation::query()
            ->whereIn('site_id', $scope->siteIdsQuery())
            ->where('support_code', $supportCode)
            ->firstOrFail();
    }

    private function invalidReference(string $field): never
    {
        throw ValidationException::withMessages([
            $field => 'The selected '.$field.' is invalid.',
        ]);
    }
}
